/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:6e5c64b2-e1b8-4630-a126-6c8ff8f4748d",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_Ca4H0p1xV",
    "aws_user_pools_web_client_id": "5v82qqu9u7a5bdl2vuau4vjrpn",
    "oauth": {}
};


export default awsmobile;
